name: Собрать плагин, через Maven

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Установить JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Собрать плагин
        run: |
          mvn -B package --file pom.xml
          VERSION=$(grep -m1 '<version>' pom.xml | sed -e 's/<[^>]*>//g' | xargs)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Формирование релиза
        id: release-form
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: Version-${{ env.VERSION }}
          name: ModernWhitelist ${{ env.VERSION }}
          body: |
            ## Первый релиз плагина
          draft: false
          prerelease: false
          generateReleaseNotes: true
      - name: Выкладывание в полученный релиз
        uses: tanyagray/action-upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.release-form.outputs.upload_url }}
          asset_path: ./target/ModernWhitelist-1.0.0.jar
          asset_name: ModernWhitelist-1.0.0.jar
          asset_content_type: application/java-archive
